# .github/workflows/deploy-docs-and-publish.yml

name: Deploy Docs & Publish

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      node-version:
        required: false
        type: string
        default: '22'
      registry-url:
        required: false
        type: string
        default: 'https://registry.npmjs.org/'
      docs-dir:
        required: false
        type: string
        default: './docs'
      docs-base-url:
        required: true
        type: string  # e.g., https://chickenjdk.github.io/github-actions-workflow
      version:
        required: false
        type: string
        default: ${{ github.ref_name }}

jobs:
  build-and-release:
    if: ${{ github.event_name != 'release' || (github.event.release.prerelease == false && github.event.release.target_commitish == 'main') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write

    env:
      VERSION: ${{ inputs['version'] }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}
          registry-url: ${{ inputs['registry-url'] }}

      - name: Install dependencies
        run: npm ci

      - name: Update package.json version
        run: |
          node -e "
          const fs = require('fs');
          const pkg = JSON.parse(fs.readFileSync('package.json'));
          pkg.version = process.env.VERSION.startsWith('v') ? process.env.VERSION.slice(1) : process.env.VERSION;
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Build
        run: npm run build

      - name: Update README.md docs URL
        run: |
          sed -i "s|${{ inputs.docs-base-url }}/docs/[^)]*|${{ inputs.docs-base-url }}/docs/${{ env.VERSION }}|g" README.md

      - name: Commit updated version + docs link
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package.json README.md
          git commit -m "chore: release ${{ env.VERSION }}" || echo "No changes to commit"
          git push origin HEAD:${{ github.event.release.target_commitish }}

      - name: Build docs with TypeDoc
        run: npm run docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.docs-dir }}
          destination_dir: docs/${{ env.VERSION }}
          keep_files: true

      - name: Rm docs directory
        run: rm -rf ${{ inputs.docs-dir }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create release
        if: github.event_name != 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs['version'] }}
          generate_release_notes: true

