name: Deploy Static Content

on:
  workflow_call:
    inputs:
      source_path:
        description: 'Relative path to item to deploy'
        required: true
        type: string
      target_subdir:
        description: 'Target subdirectory under src/$repo_name (default: basename of source_path)'
        required: false
        type: string
    secrets:
      STATIC_CONTENT_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      SRC_PATH: ${{ inputs.source_path }}
      DEST_SUBDIR: ${{ inputs.target_subdir || inputs.source_path }}

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Determine actual subdir name
        id: compute-subdir
        run: |
          if [ -z "${{ inputs.target_subdir }}" ]; then
            echo "subdir=$(basename '${{ inputs.source_path }}')" >> "$GITHUB_OUTPUT"
          else
            echo "subdir=${{ inputs.target_subdir }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Prepare files
        run: |
          mkdir -p temp-content/src/$REPO_NAME
          cp -r "${SRC_PATH}" "temp-content/src/$REPO_NAME/${{ steps.compute-subdir.outputs.subdir }}"

      - name: Checkout static-files repo
        uses: actions/checkout@v3
        with:
          repository: your-org/static-files
          token: ${{ secrets.STATIC_CONTENT_TOKEN }}
          path: static-files-repo

      - name: Copy item to repo
        run: |
          mkdir -p "static-files-repo/src/$REPO_NAME"
          rm -rf "static-files-repo/src/$REPO_NAME/${{ steps.compute-subdir.outputs.subdir }}"
          cp -r "temp-content/src/$REPO_NAME/${{ steps.compute-subdir.outputs.subdir }}" "static-files-repo/src/$REPO_NAME/"

      - name: Commit and push
        run: |
          cd static-files-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "src/$REPO_NAME/${{ steps.compute-subdir.outputs.subdir }}"
          git commit -m "Deploy static content for $REPO_NAME → ${{ steps.compute-subdir.outputs.subdir }}" || echo "Nothing to commit"
          git push
