name: Test Runner linux

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: echo "Running on self-hosted Linux runner"
      - run: sleep 1000000000
